# frozen_string_literal: true

# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto-generated by gapic-generator-ruby v0.0.1.dev.1. DO NOT EDIT!


module So
  module Much
    module Trash
      module GarbageService
        module Paths
          ##
          # Create a fully-qualified SimpleGarbage resource string.
          #
          # The resource will be in the following format:
          #
          # `projects/{project}/simple_garbage/{garbage}`
          #
          # @param project [String]
          # @param garbage [String]
          #
          # @return [String]
          def simple_garbage_path project:, garbage:
            raise ArgumentError, "project is required" if project.nil?
            raise ArgumentError, "project cannot contain /" if %r{/}.match? project
            raise ArgumentError, "garbage is required" if garbage.nil?

            "projects/#{project}/simple_garbage/#{garbage}"
          end
        end
      end
    end
  end
end
