:gem:
  :name: "google-ads-googleads"
:defaults:
  :service:
    :default_host: "ads.googleapis.com"
    :oauth_scopes:
      - https://www.googleapis.com/auth/adwords
:overrides:
  :file_path:
    google_ads: googleads
  :namespace:
    Googleads: GoogleAds
