---
:gem:
  :name: google-cloud-secretmanager-v1beta1
  :title: Secret Manager V1beta1
  :summary: Stores, manages, and secures access to application secrets.
  :env_prefix: SECRETMANAGER
:defaults:
  :service:
    :default_host: secretmanager.googleapis.com
    :oauth_scopes:
      - https://www.googleapis.com/auth/cloud-platform
:overrides:
  :namespace:
    Secretmanager: SecretManager
  :file_path:
    secret_manager: secretmanager
