inherit_gem:
  google-style: google-style.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - lib/**/*.pb.rb
    - expected_output/**/*
    - templates/default/helpers/**/*
    - test/google/gapic/annotations/**/*
    - test/google/gapic/presenters/**/*

Metrics/ClassLength:
  Max: 115
Metrics/BlockLength:
  Exclude:
    - gapic-generator.gemspec

Style/Alias:
  EnforcedStyle: prefer_alias_method
