AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - Rakefile
    - lib/**/*.pb.rb
    - expected_output/**/*
    - test/google/gapic/annotations/**/*

Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/MethodCallWithArgsParentheses:
  Enabled: true
  EnforcedStyle: omit_parentheses
  AllowParenthesesInMultilineCall: true
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/Alias:
  EnforcedStyle: prefer_alias_method
