inherit_gem:
  google-style: google-style.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - expected_output/**/*
    - templates/cloud/helpers/**/*
    - test/google/gapic/presenters/**/*

Metrics/ClassLength:
  Max: 110
Metrics/ModuleLength:
  Max: 105
